version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - D:\warehouse\heixiu\nginx-log:/var/log/nginx/
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - D:\warehouse\heixiu\minio-data:/data
    command: server /data --address ':9000' --console-address ':9001'
    environment:
      MINIO_SERVER_URL: "http://localhost/"
      MINIO_BROWSER_REDIRECT_URL: "http://localhost/console/"    
      MINIO_ROOT_USER: heixiu
      MINIO_ROOT_PASSWORD: 12345678
    # ports:
    #   - 9000
    #   - 9001
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  common-network:
    driver: bridge