version: '3.8'
services:
  postgresql-container:
    container_name: postgresql-container
    image: postgres
    # 本地映射 具体本地地址以主机路径为准
    volumes:
      - /Users/tom/person/learning/heixiu/postgresql-data:/var/lib/postgresql/data
    # https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/
    env_file:
      - ./heixiu-server/.env.production
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
      # TZ: 'Asia/Shanghai'
      # ALLOW_IP_RANGE: '0.0.0.0/0'
    # ports:
    #   - '5432:5432'
    # 4种重启策略：
    #   no：容器退出不自动重启（默认）
    #   always：容器退出总是自动重启，除非 docker stop
    #   on-failure：容器非正常退出才自动重启，还可以指定重启次数，如 on-failure:5
    #   unless-stopped：除非手动停止，否则总是会重启
    restart: on-failure:3
    networks:
      - common-network

  redis-container:
    container_name: redis-container
    image: redis
    # 本地映射 具体本地地址以主机路径为准
    # volumes:
    #   - /Users/tom/person/learning/redis-data:/data
    # ports:
    #   - '6379:6379'
    restart: on-failure:3
    networks:
      - common-network

  minio-container:
    container_name: minio-container
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ./heixiu-server/.env.production
    volumes:
      - /Users/tom/person/learning/heixiu/minio-data:/data
    command: server /data --address ':9000' --console-address ':9001'
    restart: on-failure:3
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: 20m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  nest-api:
    container_name: nest-api
    build:
      context: ./heixiu-server
      dockerfile: ./Dockerfile
    # 启动顺序
    depends_on:
      - postgresql-container
      - redis-container
      - minio-container
    # Dockerfile里面也可以指定环境变量
    # environment:
    #   - NODE_ENV=production
    env_file:
      - ./heixiu-server/.env.production
    # ports:
    #   - 6020:6020
    # 本地映射 具体本地地址以主机路径为准 一般文件使用OSS对象存储，这里图片存放到主机
    volumes:
      - /Users/tom/person/learning/heixiu/uploads:/app/uploads
      - /Users/tom/person/learning/heixiu/logs:/app/logs
    restart: on-failure:3
    networks:
      - common-network

  nginx:
    # 容器名称
    container_name: nginx-proxy
    image: nginx:alpine
    depends_on:
      - nest-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/tom/person/learning/heixiu/nginx-log:/var/log/nginx/
    ports:
      - 80:80
    restart: on-failure:3
    networks:
      - common-network

# 需要保证容器网络处于同一网络，否则容器之间无法访问
networks:
  common-network:
    driver: bridge