name: Check Errors

on:
  push:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9 

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
          key: |
            ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Run commands in multiple directories
        run: |
          for dir in meeting_room_booking_system_backend meeting_room_booking_system_frontend; do
            echo "Running commands in directory: $dir"
            cd "$dir"
            pnpm install
            pnpm build
            pnpm test
            cd ..
          done