name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: meeting_room_booking_system_backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Run commands in the aaa directory
      run: |
        npm install
        npm run build

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: meeting_room_booking_system_frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Run commands in the aaa directory
      run: |
        npm install
        npm run build